version: '2.1'

services:
  frontend:
    build: frontend_api./
    ports: 
      - "5000:80"

    depends_on:
      api:
        condition: service_healthy
    links: 
        - api

  api:
    build: dockerassignment/.
    ports: 
      - "3000:3000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000/persons"]
        interval: 30s
        timeout: 10s
        retries: 5